# DMARC => _dmarc => v=DMARC1; p=none; rua=mailto:dmarc-reports@[domain]
# SPF => [domain] => v=spf1 mx ~all

version: $DOCKER_VERSION

name: $NAME

services:
  mailserver:
    image: $IMAGE
    container_name: $NAME
    hostname: $HOSTNAME
    ports:
      - $SMTP_PORT	# SMTP - mostly processing incoming mails
      - $POP3_PORT	# POP3 - standard protocol for accessing mailbox, STARTTLS is required before client auth
      - $IMAP_PORT	# IMAP - standard protocol for accessing mailbox, STARTTLS is required before client auth
      - $SMTPS_PORT	# SMTPS - Legacy SMTPs port
      - $MSA_PORT	# MSA - SMTP port used primarily for email clients after STARTTLS and auth
      - $IMAPS_PORT	# IMAPS - alternative port for IMAP encrypted since connection
      - $POP3S_PORT	# POP3S - encrypted POP3 since connections
      - $SIEVE_PORT # Sieve
    networks:
      - admin
    volumes:
      - $DATA_VOLUME
    restart: $RESTART_POLICY

networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
