version: $DOCKER_VERSION

services:
  
  tn-guacamole:
    image: $GUACAMOLE_IMAGE
    container_name: $GUACAMOLE_NAME
    hostname: $GUACAMOLE_NAME
    environment:
      - GUACD_HOSTNAME=$GUACAMOLE_CD_NAME
      - MYSQL_HOSTNAME=$GUACAMOLE_DB_NAME
      - MYSQL_DATABASE=$GUACAMOLE_DB_DATABASE
      - MYSQL_USER=$GUACAMOLE_DB_USER
      - MYSQL_PASSWORD=$GUACAMOLE_DB_PASSWORD
    depends_on:
      - tn-guacamole-cd
      - tn-guacamole-db
    networks:    
      - datas
      - admin
    restart: $GUACAMOLE_RESTART

  tn-guacamole-cd:
    image: $GUACAMOLE_CD_IMAGE
    container_name: $GUACAMOLE_CD_NAME
    hostname: $GUACAMOLE_CD_NAME
    volumes:
      - $GUACAMOLE_CD_DRIVE_VOLUME
      - $GUACAMOLE_CD_RECORD_VOLUME
    networks:
      - admin
    restart: $GUACAMOLE_CD_RESTART

  tn-guacamole-db:
    image: $GUACAMOLE_DB_IMAGE
    container_name: $GUACAMOLE_DB_NAME
    hostname: $GUACAMOLE_DB_NAME
    environment:
      - MYSQL_USER=$GUACAMOLE_DB_USER
      - MYSQL_PASSWORD=$GUACAMOLE_DB_PASSWORD
      - MYSQL_DATABASE=$GUACAMOLE_DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$GUACAMOLE_DB_PASSWORD
    volumes:
      - $GUACAMOLE_DB_MYSQL_VOLUME
      - $GUACAMOLE_DB_MYSQL_INITSQL
    networks:    
      - datas
    restart: $GUACAMOLE_DB_RESTART

networks:
  datas:
    external: true
    name: $DOCKER_DATAS_NETWORK
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK  