version: $DOCKER_VERSION
services:
  nginxproxy:
    image: $NGINXPROXY_IMAGE
    container_name: $NGINXPROXY_CONTAINER_NAME
    environment:
      - DB_MYSQL_HOST=$NGINXPROXY_DB_CONTAINER_NAME
      - DB_MYSQL_PORT=$NGINXPROXY_DB_PORT
      - DB_MYSQL_USER=$NGINXPROXY_DB_USER
      - DB_MYSQL_PASSWORD=$NGINXPROXY_DB_PASSWORD
      - DB_MYSQL_NAME=$NGINXPROXY_DB_DATABASE
    networks:
      - proxies
      - admin
    volumes:
      - $NGINXPROXY_DATA_VOLUME
      - $NGINXPROXY_LETSENCRYPT_VOLUME
    depends_on:
      - nginxproxydb
    restart: $NGINXPROXY_RESTART

  nginxproxydb:
    image: $NGINXPROXY_DB_IMAGE
    container_name: $NGINXPROXY_DB_CONTAINER_NAME
    environment:
      - MYSQL_ROOT_PASSWORD=$NGINXPROXY_DB_PASSWORD
      - MYSQL_DATABASE=$NGINXPROXY_DB_DATABASE
      - MYSQL_USER=$NGINXPROXY_DB_USER
      - MYSQL_PASSWORD=$NGINXPROXY_DB_PASSWORD
      - MYSQL_TCP_PORT=$NGINXPROXY_DB_PORT
      - MYSQL_UNIX_PORT=$NGINXPROXY_DB_PORT
    networks:
      - admin
      - datas
    volumes:
      - $NGINXPROXY_DB_MYSQL_VOLUME
    restart: $NGINXPROXY_DB_RESTART

networks:
  proxies:
    external: true
    name: $DOCKER_PROXIES_NETWORK
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK
  datas:
    external: true
    name: $DOCKER_DATAS_NETWORK