version: $DOCKER_VERSION

services:
  tn-nginxproxy:
    image: $NGINXPROXY_IMAGE
    container_name: $NGINXPROXY_NAME
    hostname: $NGINXPROXY_NAME
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
      - '21:21'
    environment:
      DB_MYSQL_HOST: $NGINXPROXY_DB_NAME
      DB_MYSQL_PORT: $NGINXPROXY_DB_PORT
      DB_MYSQL_USER: $NGINXPROXY_DB_USER
      DB_MYSQL_PASSWORD: $NGINXPROXY_DB_PASSWORD
      DB_MYSQL_NAME: $NGINXPROXY_DB_DATABASE
    volumes:
      - $NGINXPROXY_DATA_VOLUME
      - $NGINXPROXY_LETSENCRYPT_VOLUME
    depends_on:
      - tn-nginxproxy-db
    networks:
      - datas
    restart: $NGINXPROXY_RESTART

  tn-nginxproxy-db:
    image: $NGINXPROXY_DB_IMAGE
    container_name: $NGINXPROXY_DB_NAME
    hostname: $NGINXPROXY_DB_NAME
    environment:
      MYSQL_ROOT_PASSWORD: $NGINXPROXY_DB_PASSWORD
      MYSQL_DATABASE: $NGINXPROXY_DB_DATABASE
      MYSQL_USER: $NGINXPROXY_DB_USER
      MYSQL_PASSWORD: $NGINXPROXY_DB_PASSWORD
    volumes:
      - $NGINXPROXY_DB_MYSQL_VOLUME 
    networks:
      - datas
    restart: $NGINXPROXY_DB_RESTART

networks:
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK
  datas:
    external: true
    name: $DOCKER_DATAS_NETWORK