version: $DOCKER_VERSION

services:
  tn-portainer-ce:
    image: $PORTAINER_IMAGE
    container_name: $PORTAINER_NAME
    networks:
      - admin
      - datas
    volumes:
      - $DOCKER_SOCKET
      - $PORTAINER_DATA_VOLUME
    restart: $PORTAINER_RESTART

networks:
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK
  datas:
    external: true
    name: $DOCKER_DATAS_NETWORK