version: $DOCKER_VERSION
services:
  portainer-ce:
    image: $PORTAINER_IMAGE
    container_name: $PORTAINER_CONTAINER_NAME
    networks:
      - proxies
      - admin
    volumes:
      - $DOCKER_SOCKET_LINK
      - $PORTAINER_DATA_VOLUME
    restart: $PORTAINER_RESTART

networks:
  proxies:
    external: true
    name: $DOCKER_PROXIES_NETWORK
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK
