version: $DOCKER_VERSION

services:
  tn-vscode:
    image: $SSHWIFTY_IMAGE
    container_name: $SSHWIFTY_NAME
    hostname: $SSHWIFTY_NAME
    networks:
      - admin
    restart: $SSHWIFTY_RESTART

networks:
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK