version: $DOCKER_VERSION
services:
  traefik:
    image: $TRAEFIK_IMAGE
    container_name: $TRAEFIK_CONTAINER_NAME
    ports:
      - $TRAEFIK_HTTP_PORT
      - $TRAEFIK_HTTPS_PORT
      - $TRAEFIK_NGINX_PORT
      - $TRAEFIK_TELEPORT_PORT
    volumes:
      - $DOCKER_SOCKET
      - $TRAEFIK_CONFIG_VOLUME
    networks:
      - proxies
      - admin
    restart: $TRAEFIK_RESTART 

networks:
  proxies:
    external: true
    name: $DOCKER_PROXIES_NETWORK
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK
