global:
  checkNewVersion: false

log:
  level: info

entryPoints:
  web-entry:
    address: ":80"
  websecure-entry:
    address: ":443"
  ftp-entry:
    address: ":21"
  teleport-entry-3080:
    address: ":3080"
  teleport-entry-3022:
    address: ":3022"
  teleport-entry-3023:
    address: ":3023"
  teleport-entry-3024:
    address: ":3024"
  teleport-entry-3025:
    address: ":3025"

api:
  dashboard: true
  insecure: true
  debug: true

providers:
  file:
    directory: /etc/traefik
    watch: true
    filename: config.yml