http:
  
  routers:
    
    redirect-to-https:
      entryPoints:
        - web-entry
      rule: "HostRegexp(`{host:.+}`)"
      middlewares:
        - redirect-to-https
      service: nginxproxy
      
  services:

    nginxproxy:
      loadBalancer:
        servers:
          - url: "https://google.com"   

  middlewares:

    redirect-to-https:
      redirectScheme:
        scheme: https