version: $DOCKER_VERSION
services:
  tn-vscode:
    image: $VSCODE_IMAGE
    container_name: $VSCODE_NAME
    hostname: $VSCODE_NAME
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - TZ=$DOCKER_TIMEZONE
      - PASSWORD=$VSCODE_PASSWORD
      - DEFAULT_WORKSPACE=$VSCODE_DEFAULT_WORKSPACE_DIR
    networks:
      - tn-admin-network
    volumes:
      - $VSCODE_CONFIG_VOLUME
      - $VSCODE_DOCKER_VOLUME
    restart: $VSCODE_RESTART

networks:
  tn-admin-network:
    external: true
    name: $DOCKER_ADMIN_NETWORK