version: $DOCKER_VERSION

name: sveltekit-[PUBLIC_URL_CLEAN]

services:
  sveltekit-[PUBLIC_URL_CLEAN]:
    build:
      context: $CONTEXT
      dockerfile: $DOCKER_FILE
    container_name: $NAME
    hostname: $NAME
    user: "node"
    networks:
      - admin
    restart: $RESTART_POLICY

networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
