FROM node:22-alpine

# Étape de construction
WORKDIR /app
COPY code/package*.json ./
RUN npm ci

COPY code/ ./
RUN npm run build

# Supprimer les dépendances de développement pour garder une image plus légère
RUN npm prune --production

# Configuration pour la production
ENV NODE_ENV=production
CMD ["node", "build"]
