# Dockerfile

# Use this image as the platform to run the app
FROM node:20.11-alpine

# Set the working directory for everything that will happen next
WORKDIR /app

# Copy all application files into the image
COPY . .

# Install all dependencies (including development dependencies)
RUN npm ci

# Set environment variables if necessary
ENV NODE_ENV=production

# Build the app using the 'npm build' command
CMD ["npm", "build"]
