version: $DOCKER_VERSION

services:
  tn-mailserver:
    image: $MAILSERVER_IMAGE
    container_name: $MAILSERVER_NAME
    hostname: $MAILSERVER_HOSTNAME
    env_file:
      - [DOCKER_HOME]/mailserver/.env
    ports:
      - '25:25'	# SMTP - mostly processing incoming mails
      - '110:110'	# POP3 - standard protocol for accessing mailbox, STARTTLS is required before client auth
      - '143:143'	# IMAP - standard protocol for accessing mailbox, STARTTLS is required before client auth
      - '465:465'	# SMTPS - Legacy SMTPs port
      - '587:587'	# MSA - SMTP port used primarily for email clients after STARTTLS and auth
      - '993:993'	# IMAPS - alternative port for IMAP encrypted since connection
      - '995:995'	# POP3S - encrypted POP3 since connections
      - '4190:4190' # Sieve
    networks:
      - admin
    volumes:
      - $MAILSERVER_DATA_VOLUME
    restart: $MAILSERVER_RESTART

networks:
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
