version: $DOCKER_VERSION

services:
  tn-nginxproxy:
    image: $NGINXPROXY_IMAGE
    container_name: $NGINXPROXY_NAME
    hostname: $NGINXPROXY_NAME
    env_file:
      - [DOCKER_HOME]/nginxproxy/.env
    ports:
      - $NGINXPROXY_HTTP_PORT
      - $NGINXPROXY_HTTPS_PORT
      - $NGINXPROXY_SELF_PORT
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
      DB_MYSQL_HOST: $NGINXPROXY_DB_NAME
      DB_MYSQL_USER: $NGINXPROXY_DB_USER
      DB_MYSQL_PASSWORD: $NGINXPROXY_DB_PASSWORD
      DB_MYSQL_NAME: $NGINXPROXY_DB_DATABASE
    volumes:
      - $NGINXPROXY_DATA_VOLUME
      - $NGINXPROXY_LETSENCRYPT_VOLUME
    depends_on:
      - tn-nginxproxy-db
    networks:
      - admin
      - datas
    restart: $NGINXPROXY_RESTART

  tn-nginxproxy-db:
    image: $NGINXPROXY_DB_IMAGE
    container_name: $NGINXPROXY_DB_NAME
    hostname: $NGINXPROXY_DB_NAME
    env_file:
      - [DOCKER_HOME]/nginxproxy/.env
    environment:
      MYSQL_ROOT_PASSWORD: $NGINXPROXY_DB_PASSWORD
      MYSQL_DATABASE: $NGINXPROXY_DB_DATABASE
      MYSQL_USER: $NGINXPROXY_DB_USER
      MYSQL_PASSWORD: $NGINXPROXY_DB_PASSWORD
    volumes:
      - $NGINXPROXY_DB_MYSQL_VOLUME 
    networks:
      - datas
    restart: $NGINXPROXY_DB_RESTART

networks:
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK
  datas:
    external: true
    name: $DOCKER_DATAS_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
