version: $DOCKER_VERSION

services:
  tn-portainer-ce:
    image: $PORTAINER_IMAGE
    container_name: $PORTAINER_NAME
    hostname: $PORTAINER_NAME
    env_file:
      - [DOCKER_HOME]/portainer/.env
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
    networks:
      - admin
      - datas
    volumes:
      - $DOCKER_SOCKET
      - $PORTAINER_DATA_VOLUME
    restart: $PORTAINER_RESTART

networks:
  admin:
    external: true
    name: $DOCKER_ADMIN_NETWORK
  datas:
    external: true
    name: $DOCKER_DATAS_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
