version: $DOCKER_VERSION

services:
  tn-ftpserver:
    image: $IMAGE
    container_name: $NAME
    hostname: $NAME
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
      USERS: $USERS
      ADDRESS: $ADDRESS
      MIN_PORT: $MIN_PORT
      MAX_PORT: $MAX_PORT
    ports:
      - $FTP_PORT
      - $PASSIVE_PORTS
    volumes:
      - $DATA_VOLUME
    networks:
      - admin
    restart: $RESTART

networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
