# Use an official PHP and Apache runtime as the base image
FROM php:7.4-apache

# Install required system dependencies, including oniguruma for mbstring
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libicu-dev \
    libxml2-dev \
    libmagickwand-dev \
    default-mysql-client \
    libpq-dev \
    zlib1g-dev \
    libzip-dev \
    zip \
    unzip \
    libonig-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Enable Apache modules
RUN a2enmod rewrite headers

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo_mysql intl xml mysqli pgsql pdo_pgsql zip bcmath mbstring

# Install imagick via PECL and enable it
RUN pecl install imagick \
    && docker-php-ext-enable imagick \
    && rm -rf /tmp/pear

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Laravel Installer globally via Composer
RUN composer global require laravel/installer

# Add Composer's global binaries to the system PATH
ENV PATH="$PATH:/root/.composer/vendor/bin"

# Set the ServerName directive to suppress the warning
RUN echo "ServerName php7-[PUBLIC_URL_CLEAN]" >> /etc/apache2/apache2.conf

# Start Apache
CMD ["apache2-foreground"]
