# Use an official PHP and Apache runtime as the base image
FROM php:7.4.1-apache

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libicu-dev \
    libxml2-dev \
    libmagickwand-dev \
    default-mysql-client \
    libpq-dev \
    zlib1g-dev \
    libzip-dev \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Enable Apache modules
RUN a2enmod rewrite headers

# Enable necessary PHP extensions
RUN docker-php-ext-configure gd && \
    docker-php-ext-install gd pdo_mysql intl xml mysqli pgsql pdo_pgsql zip bcmath

RUN pecl install imagick \
 && docker-php-ext-enable imagick

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the ServerName directive to suppress the warning
RUN echo "ServerName php7-[PUBLIC_URL_CLEAN]" >> /etc/apache2/apache2.conf

# Start Apache
CMD ["apache2-foreground"]

# Always leave an empty line at the end
