FROM debian:stable

ENV RUST_LOG=info

RUN mkdir /home/app

COPY ./jupiter /home/app/jupiter

WORKDIR /home/app

RUN apt-get update && apt-get install -y

RUN chmod +x /home/app/jupiter

CMD ["/home/app/jupiter", "--rpc-url", "[RPC_URL]" ]