FROM debian:stable

ENV RUST_LOG=info

COPY ./jupiter /app/jupiter

RUN apt-get update && apt-get install -y

RUN apt-get install libssl-dev openssl -y

RUN chmod +x /app/jupiter

CMD ["/app/jupiter", "--rpc-url", "[RPC_URL]" ]