FROM debian:stable

ENV RUST_LOG=info

RUN mkdir -p /home/app

COPY [DOCKER_HOME]/jupiter/[PUBLIC_URL_CLEAN]/jupiter /home/app/jupiter

WORKDIR /home/app

RUN apt-get update && apt-get install -y

RUN chmod +x /home/app/jupiter

CMD ["/home/app/jupiter", "--rpc-url", "[RPC_URL]" ]