
version: $DOCKER_VERSION

name: vaultwarden

services:
  vaultwarden:
    container_name: $NAME
    image: $IMAGE
    hostname: $NAME
    environment:
      SMTP_HOST: $SMTP_HOST
      SMTP_FROM: $SMTP_FROM
      SMTP_FROM_NAME: $SMTP_FROM_NAME
      SMTP_SECURITY: $SMTP_SECURITY
      SMTP_PORT: $SMTP_PORT
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_TIMEOUT: $SMTP_TIMEOUT
      SMTP_AUTH_MECHANISM: $SMTP_AUTH_MECHANISM
      LOGIN_RATELIMIT_MAX_BURST: $LOGIN_RATELIMIT_MAX_BURST
      LOGIN_RATELIMIT_SECONDS: $LOGIN_RATELIMIT_SECONDS
      DOMAIN: $DOMAIN
      INVITATION_ORG_NAME: $INVITATION_ORG_NAME
      INVITATIONS_ALLOWED: $INVITATIONS_ALLOWED
      ADMIN_TOKEN: $ADMIN_TOKEN
      SIGNUPS_ALLOWED: $SIGNUPS_ALLOWED
      SIGNUPS_DOMAINS_WHITELIST: $SIGNUPS_DOMAINS_WHITELIST
      SIGNUPS_VERIFY: $SIGNUPS_VERIFY
      SIGNUPS_VERIFY_RESEND_TIME: $SIGNUPS_VERIFY_RESEND_TIME
      SIGNUPS_VERIFY_RESEND_LIMIT: $SIGNUPS_VERIFY_RESEND_LIMIT
      EMERGENCY_ACCESS_ALLOWED: $EMERGENCY_ACCESS_ALLOWED
      SENDS_ALLOWED: $SENDS_ALLOWED
      WEB_VAULT_ENABLED: $WEB_VAULT_ENABLED    
    volumes:
      - $DATA_VOLUME
    networks:
      - admin 
    restart: $RESTART_POLICY

networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
