version: $DOCKER_VERSION

name: php5-[PUBLIC_URL_CLEAN]

services:
  php5-[PUBLIC_URL_CLEAN]:
    build:
      context: $CONTEXT
      dockerfile: $DOCKER_FILE
    container_name: $NAME
    hostname: $NAME
    volumes:
      - $SITE_VOLUME
      - $APACHE_SA_VOLUME
      - $APACHE_SE_VOLUME
    networks:
      - admin
    restart: $RESTART_POLICY

networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
