# Use an official PHP and Apache runtime as the base image
FROM php:5.6.40-apache-stretch

# Replace obsolete source list
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak

# Empty the sources.list file
RUN echo > /etc/apt/sources.list

# Create a new sources.list with the desired repositories
RUN echo "deb http://archive.debian.org/debian/ stretch main contrib non-free" >> /etc/apt/sources.list
RUN echo "deb http://archive.debian.org/debian/ stretch-proposed-updates main contrib non-free" >> /etc/apt/sources.list
RUN echo "deb http://archive.debian.org/debian-security stretch/updates main contrib non-free" >> /etc/apt/sources.list

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libicu-dev \
    libxml2-dev \
    libmagickwand-dev \
    && rm -rf /var/lib/apt/lists/*

# Enable Apache modules
RUN a2enmod rewrite

# Enable necessary PHP extensions
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-install gd pdo_mysql intl xml

# Set the ServerName directive to suppress the warning
RUN echo "ServerName php5-[PUBLIC_URL_CLEAN]" >> /etc/apache2/apache2.conf

# Start Apache
CMD ["apache2-foreground"]

# Always leave an empty line at the end
