version: $DOCKER_VERSION

name: supabase-directus

services:

  directus-cache:
    image: $CACHE_IMAGE
    container_name: $CACHE_NAME
    hostname: $CACHE_NAME
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
    networks:
      - admin
    restart: $CACHE_RESTART_POLICY

  directus:
    image: $IMAGE
    container_name: $NAME
    hostname: $NAME
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
      KEY: $KEY
      SECRET: $SECRET
      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      
      DB_CLIENT: $DB_TYPE
      DB_HOST: $DB_HOST
      DB_DATABASE: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASS
      DB_PORT: $DB_PORT

      CACHE_ENABLED: $CACHE_ENABLED
      CACHE_STORE: $CACHE_STORE
      REDIS: $CACHE_HOST

      CORS_ENABLED: true
      CORS_ORIGIN: false
      CORS_METHODS: GET,POST,PATCH,DELETE,OPTIONS
    volumes:
      - $UPLOADS_VOLUME
      - $EXTENSIONS_VOLUME      
    depends_on:
      - directus-cache
    networks:
      - admin
    restart: $RESTART_POLICY

networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
