version: $DOCKER_VERSION
services:
  
  db-[PUBLIC_URL_CLEAN]:
    image: $DB_IMAGE
    container_name: $DB_NAME
    hostname: $DB_NAME
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - $DB_MYSQL_VOLUME 
    networks:
      - datas
    restart: $DB_RESTART_POLICY

  cache-[PUBLIC_URL_CLEAN]:
    image: $CACHE_IMAGE
    container_name: $CACHE_NAME
    hostname: $CACHE_NAME
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
    networks:
      - datas
    restart: $CACHE_RESTART_POLICY

  directus-[PUBLIC_URL_CLEAN]:
    image: $IMAGE
    container_name: $NAME
    hostname: $NAME
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
      KEY: $KEY
      SECRET: $SECRET
      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      PUBLIC_URL: $PUBLIC_URL
      
      DB_CLIENT: $DB_TYPE
      DB_HOST: $DB_NAME
      DB_DATABASE: $DB_DATABASE
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD

      CACHE_ENABLED: $CACHE_ENABLED
      CACHE_STORE: $CACHE_STORE
      CACHE_REDIS: $CACHE_HOST
    volumes:
      - $UPLOADS_VOLUME
      - $EXTENSIONS_VOLUME      
    depends_on:
      - cache-[PUBLIC_URL]
      - db-[PUBLIC_URL]
    networks:
      - admin
    restart: $RESTART_POLICY

networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
