version: $DOCKER_VERSION

name: mysql5-[PUBLIC_URL_CLEAN]

services:  
  mysql5-[PUBLIC_URL_CLEAN]:
    image: $MYSQL_IMAGE
    container_name: $MYSQL_NAME
    hostname: $MYSQL_NAME
    environment:
      PUID: $DOCKER_UID
      PGID: $DOCKER_GID
      MYSQL_ROOT_PASSWORD: $MYSQL_DB_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB_DATABASE
      MYSQL_USER: $MYSQL_DB_USER
      MYSQL_PASSWORD: $MYSQL_DB_PASSWORD
    volumes:
      - $MYSQL_VOLUME
      - $MYSQL_INIT_VOLUME
    networks:
      - admin
    restart: $MYSQL_RESTART_POLICY
    
networks:
  admin:
    external: true
    name: $DOCKER_NETWORK

# ALWAYS LEAVE BLANK LINE AT THE END
